### ISSUE TITLE
Maintainer on Hackage

### ISSUE THREAD

**Issue by ChristopherKing42** [chrisdone/codepad#2]
I could become the maintainer (it would be my first package.) I see that the maintainer is currently listed as none.

**Comment by chrisdone** [comment]
I'm not maintaining it anymore, haven't used it for years. What's your hackage username?

**Comment by TheKing42** [comment]
I am https://hackage.haskell.org/user/TheKing . This would be my first Hackage package (I'll try to take care of it, though it looks like the amount of maintenance will be minimal. I think I will try and do the Haddock syntax linking thing though.)

**Comment by TheKing42** [comment]
Can I maintain it?

**Comment by chrisdone** [comment]
Added as maintainer!

**Comment by TheKing42** [comment]
Cool, should I continue to use this repo, or just use my fork?

**Comment by chrisdone** [comment]
If you delete your fork I can transfer ownership of this one to you.

**Comment by TheKing42** [comment]
I deleted it.
